

server:
  port: 8010

spring:
  application:
    name: discoveryservice


    #logging:
    #  level:
#    root: DEBUG

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    hostname: localhost
    lease-expiration-duration-in-seconds: 30

